import createClient from 'openapi-fetch'

import type { components, paths } from '../contracts/schema'

/**
 * The single typed HTTP client over the generated FastAPI contract.
 * `paths` is generated by `openapi-typescript` from the committed
 * `src/contracts/openapi.json`; no backend-owned enum or wire schema is
 * duplicated by hand in the frontend.
 */
export const api = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_BASE_URL ?? '',
})

export type { components, paths }
export type ApiPaths = paths

export type ApiErrorBody = {
  detail?: unknown
} & Record<string, unknown>

export function apiErrorMessage(error: unknown, response?: Response): string {
  if (response) {
    if (response.status === 401) return 'Missing or invalid actor identity.'
    if (response.status === 403) return 'Not authorized for this project.'
    if (response.status === 404) return 'Not found in this project.'
  }
  if (typeof error === 'object' && error !== null && 'detail' in error) {
    const detail = (error as ApiErrorBody).detail
    if (typeof detail === 'string') return detail
  }
  return 'Request failed.'
}
