// Generates `src/contracts/enums.generated.ts` from the committed FastAPI
// OpenAPI snapshot. The runtime enum value arrays used by UI form controls come
// from this generated module — never from a hand-maintained registry.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const spec = JSON.parse(readFileSync(path.join(root, 'src/contracts/openapi.json'), 'utf8'))
const schemas = spec.components.schemas

// Core-owned enum schemas the workspace renders as typed choice lists.
const enumNames = [
  'ObjectType',
  'RelationType',
  'EvidenceKind',
  'EvidenceRole',
  'Polarity',
  'Confidence',
  'CitedAs',
  'DecisionStatus',
  'ResourceKind',
  'EvidenceTargetKind',
  'CapabilityKind',
  'ProviderRuntimeHealth',
  'CapabilityAvailability',
  'Role',
  'ProjectVisibility',
  'ToolSource',
  'AgentToolAutonomy',
]

const constName = (name) =>
  ({
    ObjectType: 'OBJECT_TYPES',
    RelationType: 'RELATION_TYPES',
    EvidenceKind: 'EVIDENCE_KINDS',
    EvidenceRole: 'EVIDENCE_ROLES',
    Polarity: 'POLARITIES',
    Confidence: 'CONFIDENCES',
    CitedAs: 'CITED_AS',
    DecisionStatus: 'DECISION_STATUSES',
    ResourceKind: 'RESOURCE_KINDS',
    EvidenceTargetKind: 'EVIDENCE_TARGET_KINDS',
    CapabilityKind: 'CAPABILITY_KINDS',
    ProviderRuntimeHealth: 'PROVIDER_RUNTIME_HEALTHS',
    CapabilityAvailability: 'CAPABILITY_AVAILABILITIES',
    Role: 'ROLES',
    ProjectVisibility: 'PROJECT_VISIBILITIES',
    ToolSource: 'TOOL_SOURCES',
    AgentToolAutonomy: 'AGENT_TOOL_AUTONOMIES',
  })[name]

const lines = [
  '// @generated by scripts/generate-enums.mjs — do not edit by hand.',
  '// The runtime enum value lists below are the only frontend source for the',
  '// backend-owned domain vocabulary (FastAPI owns the wire contract).',
  "import type { components } from './schema'",
  '',
]

for (const name of enumNames) {
  const schema = schemas[name]
  if (!schema || !Array.isArray(schema.enum)) {
    throw new Error(`expected enum schema ${name} in openapi.json`)
  }
  lines.push(
    `export const ${constName(name)}: readonly components['schemas']['${name}'][] = ${JSON.stringify(
      schema.enum,
    )} as const`,
  )
  lines.push('')
}

writeFileSync(path.join(root, 'src/contracts/enums.generated.ts'), lines.join('\n'))
console.log(`wrote src/contracts/enums.generated.ts (${enumNames.length} enums)`)
