// @generated by scripts/generate-enums.mjs — do not edit by hand.
// The runtime enum value lists below are the only frontend source for the
// backend-owned domain vocabulary (FastAPI owns the wire contract).
import type { components } from './schema'

export const OBJECT_TYPES: readonly components['schemas']['ObjectType'][] = ["protein","sequence","structure","variant","ligand","complex","dataset","assay","construct","other"] as const

export const RELATION_TYPES: readonly components['schemas']['RelationType'][] = ["variant_of","derived_from","represents","evaluates","consumed_as_input_by","produced","imported_as","selects","supersedes","cites"] as const

export const EVIDENCE_KINDS: readonly components['schemas']['EvidenceKind'][] = ["experimental","literature","computation","observation","note"] as const

export const EVIDENCE_ROLES: readonly components['schemas']['EvidenceRole'][] = ["primary_support","corroborating","background","methodology","negative_result","hypothesis"] as const

export const POLARITIES: readonly components['schemas']['Polarity'][] = ["supports","contradicts","neutral"] as const

export const CONFIDENCES: readonly components['schemas']['Confidence'][] = ["low","med","high"] as const

export const CITED_AS: readonly components['schemas']['CitedAs'][] = ["supports","contradicts","context"] as const

export const DECISION_STATUSES: readonly components['schemas']['DecisionStatus'][] = ["draft","committed"] as const

export const RESOURCE_KINDS: readonly components['schemas']['ResourceKind'][] = ["scientific_object_series","scientific_object_revision","run_reference","session_reference","artifact_reference","literature_reference","external_reference"] as const

export const EVIDENCE_TARGET_KINDS: readonly components['schemas']['EvidenceTargetKind'][] = ["scientific_object_revision","decision","evidence"] as const
