"""phase1 scientific context core + authority substrate

Revision ID: 42bee4363564
Revises: 
Create Date: 2026-09-08 18:30:33.187728
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '42bee4363564'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('external_identities',
    sa.Column('external_identity_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('external_identity_id'),
    sa.UniqueConstraint('authority', 'native_id', name='uq_external_identity_authority_native')
    )
    op.create_table('global_resource_registry',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('resource_kind', sa.Enum('scientific_object_series', 'scientific_object_revision', 'run_reference', 'session_reference', 'artifact_reference', 'literature_reference', 'external_reference', name='resource_kind', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'shared_with_members', name='project_visibility', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_references',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('version_id', sa.String(length=200), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('authority', 'native_id', 'version_id', name='uq_artifact_identity')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'committed', name='decision_status', native_enum=False), nullable=False),
    sa.Column('next_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('draft_cites', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('draft_selects', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('committed_by', sa.Uuid(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['committed_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_table('external_references',
    sa.Column('external_reference_id', sa.Uuid(), nullable=False),
    sa.Column('external_identity_id', sa.Uuid(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['external_identity_id'], ['external_identities.external_identity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_reference_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_reference_id')
    )
    op.create_index(op.f('ix_external_references_external_identity_id'), 'external_references', ['external_identity_id'], unique=False)
    op.create_table('global_provenance_edges',
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('variant_of', 'derived_from', 'represents', 'evaluates', 'consumed_as_input_by', 'produced', 'imported_as', 'selects', 'supersedes', 'cites', name='relation_type', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_kind', sa.Enum('scientific_object_series', 'scientific_object_revision', 'run_reference', 'session_reference', 'artifact_reference', 'literature_reference', 'external_reference', name='resource_kind', native_enum=False), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.Enum('scientific_object_series', 'scientific_object_revision', 'run_reference', 'session_reference', 'artifact_reference', 'literature_reference', 'external_reference', name='resource_kind', native_enum=False), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_id <> target_id', name='ck_global_edge_not_self'),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['global_resource_registry.resource_id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['global_provenance_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['global_resource_registry.resource_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_global_provenance_edges_source_id'), 'global_provenance_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_global_provenance_edges_target_id'), 'global_provenance_edges', ['target_id'], unique=False)
    op.create_table('literature_references',
    sa.Column('literature_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('literature_id'),
    sa.UniqueConstraint('authority', 'native_id', name='uq_literature_authority_native')
    )
    op.create_table('project_memberships',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', 'viewer', name='project_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'actor_id')
    )
    op.create_index(op.f('ix_project_memberships_actor_id'), 'project_memberships', ['actor_id'], unique=False)
    op.create_index(op.f('ix_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False)
    op.create_table('resource_stewardships',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('steward_project_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steward_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resource_stewardships_resource_id'), 'resource_stewardships', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_stewardships_steward_project_id'), 'resource_stewardships', ['steward_project_id'], unique=False)
    op.create_table('run_references',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('input_parameter_digest', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('authority', 'native_id', name='uq_run_authority_native')
    )
    op.create_table('scientific_object_series',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('protein', 'sequence', 'structure', 'variant', 'ligand', 'complex', 'dataset', 'assay', 'construct', 'other', name='object_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('session_references',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('authority', 'native_id', name='uq_session_authority_native')
    )
    op.create_table('decision_supersedes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('superseded_decision_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', name='uq_supersedes_out'),
    sa.UniqueConstraint('superseded_decision_id', name='uq_supersedes_in')
    )
    op.create_index(op.f('ix_decision_supersedes_project_id'), 'decision_supersedes', ['project_id'], unique=False)
    op.create_table('decision_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.Enum('scientific_object_series', 'scientific_object_revision', 'run_reference', 'session_reference', 'artifact_reference', 'literature_reference', 'external_reference', name='resource_kind', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['global_resource_registry.resource_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'target_id', name='uq_decision_target_once')
    )
    op.create_index(op.f('ix_decision_targets_decision_id'), 'decision_targets', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_targets_target_id'), 'decision_targets', ['target_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('experimental', 'literature', 'computation', 'observation', 'note', name='evidence_kind', native_enum=False), nullable=False),
    sa.Column('role', sa.Enum('primary_support', 'corroborating', 'background', 'methodology', 'negative_result', 'hypothesis', name='evidence_role', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('polarity', sa.Enum('supports', 'contradicts', 'neutral', name='evidence_polarity', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'med', 'high', name='evidence_confidence', native_enum=False), nullable=True),
    sa.Column('confidence_source', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_resource_id', sa.Uuid(), nullable=True),
    sa.Column('source_kind', sa.Enum('scientific_object_series', 'scientific_object_revision', 'run_reference', 'session_reference', 'artifact_reference', 'literature_reference', 'external_reference', name='resource_kind', native_enum=False), nullable=True),
    sa.Column('target_revision_id', sa.Uuid(), nullable=True),
    sa.Column('target_decision_id', sa.Uuid(), nullable=True),
    sa.Column('target_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(CASE WHEN target_revision_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN target_decision_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN target_evidence_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_evidence_exactly_one_target'),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_resource_id'], ['global_resource_registry.resource_id'], ),
    sa.ForeignKeyConstraint(['target_decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_revision_id'], ['global_resource_registry.resource_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('scientific_object_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['scientific_object_series.series_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'alias', name='uq_alias_series_value')
    )
    op.create_index(op.f('ix_scientific_object_aliases_series_id'), 'scientific_object_aliases', ['series_id'], unique=False)
    op.create_table('scientific_object_external_identities',
    sa.Column('external_identity_id', sa.Uuid(), nullable=False),
    sa.Column('qualifier', sa.String(length=100), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['external_identity_id'], ['external_identities.external_identity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['scientific_object_series.series_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_identity_id', 'qualifier')
    )
    op.create_index(op.f('ix_scientific_object_external_identities_external_identity_id'), 'scientific_object_external_identities', ['external_identity_id'], unique=False)
    op.create_index(op.f('ix_scientific_object_external_identities_series_id'), 'scientific_object_external_identities', ['series_id'], unique=False)
    op.create_table('scientific_object_revision',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('revision_seq', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.Enum('protein', 'sequence', 'structure', 'variant', 'ligand', 'complex', 'dataset', 'assay', 'construct', 'other', name='object_type', native_enum=False), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['scientific_object_series.series_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('series_id', 'revision_seq', name='uq_revision_series_seq')
    )
    op.create_index(op.f('ix_scientific_object_revision_series_id'), 'scientific_object_revision', ['series_id'], unique=False)
    op.create_table('decision_evidence',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('cited_as', sa.Enum('supports', 'contradicts', 'context', name='cited_as', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'evidence_id')
    )
    op.create_index(op.f('ix_decision_evidence_decision_id'), 'decision_evidence', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_evidence_id'), 'decision_evidence', ['evidence_id'], unique=False)
    op.create_table('project_resource_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('folder', sa.String(length=500), nullable=True),
    sa.Column('annotation', sa.String(length=1000), nullable=True),
    sa.Column('preferred_revision_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_revision_id'], ['scientific_object_revision.revision_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['global_resource_registry.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'resource_id', name='uq_link_project_resource')
    )
    op.create_index(op.f('ix_project_resource_links_project_id'), 'project_resource_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_resource_links_resource_id'), 'project_resource_links', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_resource_links_resource_id'), table_name='project_resource_links')
    op.drop_index(op.f('ix_project_resource_links_project_id'), table_name='project_resource_links')
    op.drop_table('project_resource_links')
    op.drop_index(op.f('ix_decision_evidence_evidence_id'), table_name='decision_evidence')
    op.drop_index(op.f('ix_decision_evidence_decision_id'), table_name='decision_evidence')
    op.drop_table('decision_evidence')
    op.drop_index(op.f('ix_scientific_object_revision_series_id'), table_name='scientific_object_revision')
    op.drop_table('scientific_object_revision')
    op.drop_index(op.f('ix_scientific_object_external_identities_series_id'), table_name='scientific_object_external_identities')
    op.drop_index(op.f('ix_scientific_object_external_identities_external_identity_id'), table_name='scientific_object_external_identities')
    op.drop_table('scientific_object_external_identities')
    op.drop_index(op.f('ix_scientific_object_aliases_series_id'), table_name='scientific_object_aliases')
    op.drop_table('scientific_object_aliases')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_decision_targets_target_id'), table_name='decision_targets')
    op.drop_index(op.f('ix_decision_targets_decision_id'), table_name='decision_targets')
    op.drop_table('decision_targets')
    op.drop_index(op.f('ix_decision_supersedes_project_id'), table_name='decision_supersedes')
    op.drop_table('decision_supersedes')
    op.drop_table('session_references')
    op.drop_table('scientific_object_series')
    op.drop_table('run_references')
    op.drop_index(op.f('ix_resource_stewardships_steward_project_id'), table_name='resource_stewardships')
    op.drop_index(op.f('ix_resource_stewardships_resource_id'), table_name='resource_stewardships')
    op.drop_table('resource_stewardships')
    op.drop_index(op.f('ix_project_memberships_project_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_actor_id'), table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_table('literature_references')
    op.drop_index(op.f('ix_global_provenance_edges_target_id'), table_name='global_provenance_edges')
    op.drop_index(op.f('ix_global_provenance_edges_source_id'), table_name='global_provenance_edges')
    op.drop_table('global_provenance_edges')
    op.drop_index(op.f('ix_external_references_external_identity_id'), table_name='external_references')
    op.drop_table('external_references')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('artifact_references')
    op.drop_table('projects')
    op.drop_table('global_resource_registry')
    op.drop_table('external_identities')
    op.drop_table('actors')
    # ### end Alembic commands ###
