"""phase3 external provider credential binding

Revision ID: fdd753899c9f
Revises: 42bee4363564
Create Date: 2026-09-09 10:13:21.459625
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fdd753899c9f'
down_revision: str | None = '42bee4363564'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_provider_credential_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('secret_ref', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'provider_key', 'kind', name='uq_credential_binding_actor_provider_kind')
    )
    op.create_index(op.f('ix_external_provider_credential_bindings_actor_id'), 'external_provider_credential_bindings', ['actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_provider_credential_bindings_actor_id'), table_name='external_provider_credential_bindings')
    op.drop_table('external_provider_credential_bindings')
    # ### end Alembic commands ###
